In [5]:
# https://pysource.com/instance-segmentation-mask-rcnn-with-python-and-opencv
import cv2
import numpy as np

# Loading Mask RCNN
net = cv2.dnn.readNetFromTensorflow("dnn/frozen_inference_graph_coco.pb","dnn/mask_rcnn_inception_v2_coco_2018_01_28.pbtxt")

# Generate random colors
colors = np.random.randint(0, 255, (80, 3))

print(colors)

# Load image
img = cv2.imread("car.jpg") 
height, width, _ = img.shape

# Create black image
black_image = np.zeros((height, width, 3), np.uint8)
black_image[:] = (100, 100, 0)

# Detect objects
blob = cv2.dnn.blobFromImage(img, swapRB=True)
net.setInput(blob)

boxes, masks = net.forward(["detection_out_final", "detection_masks"])
detection_count = boxes.shape[2]

for i in range(detection_count):
    box = boxes[0, 0, i]
    class_id = box[1]
    score = box[2]
    if score < 0.5:
        continue 

# Get box Coordinates
x = int(box[3] * width)
y = int(box[4] * height)
x2 = int(box[5] * width)
y2 = int(box[6] * height)

roi = black_image[y: y2, x: x2]
roi_height, roi_width, _ = roi.shape

# Get the mask
mask = masks[i, int(class_id)]
mask = cv2.resize(mask, (roi_width, roi_height))
_, mask = cv2.threshold(mask, 0.5, 255, cv2.THRESH_BINARY)

cv2.rectangle(img, (x, y), (x2, y2), (255, 0, 0), 3)

# Get mask coordinates
contours, _ = cv2.findContours(np.array(mask, np.uint8), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
color = colors[int(class_id)]
for cnt in contours:
    cv2.fillPoly(roi, [cnt], (int(color[0]), int(color[1]), int(color[2])))

# cv2.imshow("roi", roi)
# cv2.waitKey(0)


cv2.imshow("Image", img)
cv2.imshow("Black image", black_image)
cv2.waitKey(0)

[[ 11  20  17]
 [ 68 206  61]
 [220 101  89]
 [194 141  10]
 [ 58  94 234]
 [169 177 102]
 [127  46  97]
 [  8  41 118]
 [128  79 242]
 [ 82  51 131]
 [247  87  14]
 [166 164  19]
 [230 248 147]
 [  9 176  31]
 [243  52  19]
 [170  29  66]
 [ 42 117 236]
 [200  32   9]
 [235  64 212]
 [ 13 158 117]
 [ 60 185   3]
 [198  79 192]
 [ 93  86 110]
 [137  17 230]
 [148 108 204]
 [235  20  81]
 [137 239 106]
 [ 45  53  38]
 [157 138 212]
 [ 69 223 151]
 [ 71   9 124]
 [ 68 200  25]
 [197 126 126]
 [  9  13  45]
 [236  64 146]
 [194 163   9]
 [117 109 123]
 [111   5 182]
 [217 221  31]
 [ 76 176  59]
 [ 13 166 201]
 [238 193 146]
 [187 200 126]
 [235 150  85]
 [154 200  29]
 [251 232 146]
 [ 84 183  83]
 [137 246 132]
 [115 168 180]
 [180 112 167]
 [150  22 254]
 [ 39 115  78]
 [ 80 119 240]
 [124  67 120]
 [240  72  72]
 [ 38  65  26]
 [253   6 106]
 [ 48  10 236]
 [ 32 247 172]
 [186 175 192]
 [169 225 100]
 [165  57 249]
 [  0  88 110]
 [ 34 163 233]
 [142 113 227]
 [211 176  42]
 [177 161 

error: OpenCV(4.5.2) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-inblc7p7\opencv\modules\imgproc\src\resize.cpp:4054: error: (-215:Assertion failed) inv_scale_x > 0 in function 'cv::resize'
